### ISSUE TITLE
你好，找不到你的联系方式

### ISSUE THREAD

**Issue by njzhenghao** [HuiMi24/crysadm#3]
所以就来这里发了
我fork了一下你的云监工，准备修改一下安装脚本和升级到最新版本，再发布，可以吗？没看到你的许可证类型，觉得还是来这里说一下比较好

**Comment by HuiMi24** [comment]
没问题，你发布吧。云监工的原始代码也是fork别人的，他也没有指定许可。如果有什么问题，大家可以一起交流。

**Comment by njzhenghao** [comment]
好的，谢谢了
