### ISSUE TITLE
频繁502

### ISSUE THREAD

**Issue by reizhi** [HuiMi24/crysadm#5]
系统Debian 8.6，python 3.6.0，redis 2.8.17，uWSGI 2.0.14，nginx 1.11.7
端口80，只要开着云监工任意网页，不到几分钟就502。不打开可以持续正常运行。
日志看不到任何报错信息

**Comment by HuiMi24** [comment]
请尝试先杀掉所有的crysadm相关进程，然后再重启nginx，以及crysadm

**Comment by 986559635** [comment]
Thanks for your prompt reply.
