### ISSUE TITLE
添加迅雷账号失败，错误信息：协议不合法，请联系客服确认

### ISSUE THREAD

**Issue by monokoo** [HuiMi24/crysadm#7]
后来查询了资料发现是因为服务器是国外IP，现在迅雷官方加了验证码机制导致的登录失败。希望能针对这种情况添加自动识别验证码的功能，或者手动填写也可以。谢谢了

**Comment by HuiMi24** [comment]
我也发现了这个问题，临时的解决方案是把监工移到国内的服务器上来。最近比较忙，有时间了我会研究一下能否获取验证码
